config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }

  put "like_user/:id", to: "profiles#upvote", as: :like_user

  resources :pictures do
    member do
      put "like", to: "pictures#upvote"
    end
  end

  # custom routes for users
  get '/users/:id/' => 'users#show', :as => :user
  patch '/users/:id/' => 'users#follow'
  get '/users/' => 'users#index', :as => :all_users

  # custom route for landing page
  get '/home' => 'pictures#landing', :as => :home

  # custom bubble bar search route
  get '/bubbleBar', :to => 'pictures#bubbleBarSearch'

  # root "pictures#landing"
  root "pictures#landing"

end

app/models/user.rb
class User < ActiveRecord::Base

  # make searchable
  #
  searchkick word_start: [:user]

  acts_as_votable

  # exclude rating from searches until I figure out
  # how to avoid the mapper_parsing/number_format_exception
  def search_data
    attributes.except(:rating)
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable

  has_many :pictures, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :following, dependent: :destroy
  accepts_nested_attributes_for :pictures, :allow_destroy => true
  accepts_nested_attributes_for :profile, :allow_destroy => true

  validates :username,
    :presence => false,
    :uniqueness => {
      :case_sensitive => false
    }

  validate :validate_username

  # additional attrs for UI processing
  #
  attr_accessor :artist
  # at signup time, a user can upload up to 5 pictures
  # these will get added to the database at signup time
  #
  attr_accessor :pictures[5]
  serialize :pictures, Array

  attr_accessor :keywords[5]
  serialize :keywords, Array


  # currently adding an array of pictures is not working.
  # hardcoding five separate possible pictures instead.
  #
  attr_accessor :picture1
  attr_accessor :picture2
  attr_accessor :picture3
  attr_accessor :picture4
  attr_accessor :picture5

  # keywords automatically added at upload time
  #
  attr_accessor :keywordStr1
  attr_accessor :keywordStr2
  attr_accessor :keywordStr3
  attr_accessor :keywordStr4
  attr_accessor :keywordStr5

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      # the use of 'lower' in mySQL may result in any index on the email column to be ignored.
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_hash).first
    end
  end

  protected

  def profile
    super || build_profile
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

   before_action :configure_permitted_parameters, if: :devise_controller?
   after_action :set_profile, only: [:create]

  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys:
      [:email, :username, :password, :password_confirmation, :remember_me, :profile_id,
        {pictures: []}, profile_attributes: [
          :id, :brandname, :description, :avatar, :heroImage, :street, :street2, :city, :state, :zip
        ]
      ]
    )
     devise_parameter_sanitizer.permit(:account_update, keys:
      [:email, :username, :remember_me, :profile_id,
        {pictures: []}, profile_attributes: [
          :id, :brandname, :description, :avatar, :heroImage, :street, :street2, :city, :state, :zip
        ]
      ]
    )
  end

  def create
    super

      if params[:user][:pictures].present?
        # array input not currently working
        #
   #      puts ""
   #      puts "There are #{params[:pictures].length} Pictures uploaded!"
   #      puts ""
      # params[:user][:pictures].each { |image|
      #   puts "Checking for image #{'-' * 20}"
      #   @user.pictures.build(image: image) if image.present?
      # }

      end

      msg = ""
    if params[:user][:picture1].present?

      @user.pictures.build(image: params[:user][:picture1])
      @user.pictures.last.save
      picture_id = @user.pictures.last.id

      keywords = Keywords.keywordStringToKeywords(params[:keywordStr1])

      keywords.each do |kw|
        keyword = Keyword.new do |x|
          x.picture_id = picture_id
          x.word = kw
          x.hidden = true
        end
        if !keyword.save
          msg += "keyword #{kw} add failure. "
        end
      end

    end

    if params[:user][:picture2].present?
      @user.pictures.build(image: params[:user][:picture2])
      @user.pictures.last.save
      picture_id = @user.pictures.last.id

      keywords = Keywords.keywordStringToKeywords(params[:keywordStr2])

      puts("Img2: " + params[:keywordStr2]);

      keywords.each do |kw|
        keyword = Keyword.new do |x|
          x.picture_id = picture_id
          x.word = kw
          x.hidden = true
        end
        if !keyword.save
          msg += "keyword #{kw} add failure. "
        end
      end

    end

    if params[:user][:picture3].present?
      @user.pictures.build(image: params[:user][:picture3])
      @user.pictures.last.save
      picture_id = @user.pictures.last.id

      keywords = Keywords.keywordStringToKeywords(params[:keywordStr3])
      puts("Img3: " + params[:keywordStr3]);

      keywords.each do |kw|
        keyword = Keyword.new do |x|
          x.picture_id = picture_id
          x.word = kw
          x.hidden = true
        end
        if !keyword.save
          msg += "keyword #{kw} add failure. "
        end
      end
    end

    if params[:user][:picture4].present?
      @user.pictures.build(image: params[:user][:picture4])
      @user.pictures.last.save
      picture_id = @user.pictures.last.id

      keywords = Keywords.keywordStringToKeywords(params[:keywordStr4])
      puts("Img4: " + params[:keywordStr4]);

      keywords.each do |kw|
        keyword = Keyword.new do |x|
          x.picture_id = picture_id
          x.word = kw
          x.hidden = true
        end
        if !keyword.save
          msg += "keyword #{kw} add failure. "
        end
      end
    end

    if params[:user][:picture5].present?
      @user.pictures.build(image: params[:user][:picture5])
      @user.pictures.last.save
      picture_id = @user.pictures.last.id

      keywords = Keywords.keywordStringToKeywords(params[:keywordStr5])
      puts("Img5: " + params[:keywordStr5]);

      keywords.each do |kw|
        keyword = Keyword.new do |x|
          x.picture_id = picture_id
          x.word = kw
          x.hidden = true
        end
        if !keyword.save
          msg += "keyword #{kw} add failure. "
        end
      end
    end

  end

  def set_profile
    if User.count > 0
      u = User.last
      p = Profile.last
      u.profile_id = p.id
      # all users default to level 1
      p.level = 1
      p.save
      u.save
    end
  end

  def new
    # take the lesser of total pictures and 100 and put
    # half that number of pictures in each picture display
    # array without duplicating pictures.
    #
    totalPix = Picture.count > 100 ? 100 : Picture.count

    @displayPix = Picture.limit(totalPix).order("RANDOM()")
    @displayPixH = [];
    @displayPixV = [];

    if ( totalPix%2 == 0 )
      @displayPixH = @displayPix[0..(totalPix/2)-1]
      @displayPixV = @displayPix[totalPix/2..totalPix-1]
    else
      @displayPixH = @displayPix[0..(totalPix-1)/2]
      @displayPixV = @displayPix[(totalPix-1)/2 + 1..totalPix-1]
    end
    super

  end

  def update
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:follow,:show,:update]
  before_action :find_profile, only: [:show,:update]

  def destroy
    # find all related follow records
    super
  end

  def follow

    profile = Profile.find(current_user.profile_id)
    profile2 = Profile.find(@user.profile_id)
    if params[:follow] == 'on'
      # current_user wants to follow user
      #
      chase = Following.new();
      chase.follower = current_user.id
      chase.following = @user.id
      chase.save

      puts '-' * 30
      puts profile.brandname + ' now follows ' + profile2.brandname
      puts '-' * 30
    else
      # current user wants to unfollow user
      #

      follows = Following.where("follower = #{current_user.id} AND following = #{@user.id}")
      if follows.length !=1
        puts "error attempting to unfollow, #{follows.length} records found, should be 1"
      else
        follows[0].destroy
      end

      puts '*' * 30
      puts profile.brandname + ' stopped following ' + profile2.brandname
      puts '*' * 30
    end

    # respond_to do |format|
    #   # all updating is takencare of in javascript, no action necessary here
    #   # a 406 error is returned by the server, but there's no consequence to the user
    # end

  end

  def patch

  end

  def index
    @users = User.all.order("created_at DESC")
  end

  def show
    @pics = @user.pictures()
    @freePix = @pics[0..4]
    @userPix = @pics.drop(5)
    @following = is_following
    if !current_user.nil? && current_user == @user
      @following_list = Following.where("follower = #{current_user.id}")
    end

  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Profile successfully updated"
    else
      render "edit"
    end
  end

private
  def picture_params
    # params.require(:picture).permit(:title, :description, :image, :profile_id)
    params.require(:picture).permit(:title, :description, :image)
  end

  def user_params
    params.require(:user).permit(:email, :username, profile_attributes: [:brandname, :avatar, :description, :heroImage])
  end

  def find_user
    @user = User.find(params[:id])
  end

  def find_profile
    @profile = Profile.find(@user.profile_id)
  end

  # return whether current_user is following @user
  #
  def is_following
    follows = []
    following = false
    if !current_user.nil? && current_user != @user
      follows = Following.where("follower = #{current_user.id} AND following = #{@user.id}")
    end
    if follows.length != 0
      following = true
    end

    return following
  end

end

app/views/users/_follow.html.haml
- if user_signed_in? && current_user != @user
  = form_for @user, html: { multipart: true, remote: true, class: "profileForm"} do |f|
    - if @following == true
      %input.profile#follow{:type => 'checkbox', :name=>'follow', :alt=>"follow this artist", :checked=>'checked'}
    - else
      %input.profile#follow{:type => 'checkbox', :name=>'follow', :alt=>"follow this artist"}
    %label.profile#follow{'for'=>'follow'}

app/views/users/index.html.haml
.indexPage
  - @users.each_with_index do |u|
    .indexTile
      - p = Profile.find_by(user_id: u.id)
      - avatar = p.avatar ? p.avatar.url(:medium) : "missing_avatar.png"
      .row.center
        = link_to u do
          .profileAvatar{:style => %(background:url("#{avatar}"); background-size: contain; background-position: 50%; background-repeat: no-repeat)}
      .row.center
        %p.profileBrandLevel
          = link_to p.brandname, u
        .lvl.lvlc4.profileBrandLevel
          = p.level

app/views/users/show.html.haml
.row.signupTop
  - if @profile.heroImage.present?
    :javascript
      setHeroImage("#{@profile.heroImage}");
  - else
    .placeholderBlock
.col-md-3
  = image_tag @profile.avatar.url(:medium)
  %ul.profileMenu
    %li= image_tag 'proficons.png'

    .row
      .col-md-4
        = link_to like_user_path(@user), method: :put, class: "btn btn-default" do
          %span.glyphicon.glyphicon-heart{ :alt=>"favorite this artist"}
            =@user.get_upvotes.size
      .col-md-4
        = render 'follow'
      .col-md-4
        rate
    - if @user.rating > 0
      .star-rating{ "data-score" => @user.rating }

    %li= link_to "Read Reviews", "#"

    - if user_signed_in? && current_user != @user
      %li= link_to "Message this Artist", "#"
    %li= link_to "Set Keyword Alerts", "#"
    %li= link_to "Set Banking Information", "#"
    %li= link_to "Account Settings", "#"
    %li= link_to "Manage Reviews", "#"

.col-md-9.profilePagePadding
  %span
    %h1.profileBrandLevel
      = @profile.brandname
    .lvl.lvlc4.profileBrandLevel
      = @profile.level

  %h3= @profile.description

  %h3 Free Images
  .row
    - @freePix.each do |pic|
      .col-md-5ths.col-xs_6
        .featuredTile
          = link_to (image_tag pic.image.url(:small)), pic
  .row
    #signupGal
      - @userPix.each do |pic|
        .imageFrame
          = link_to (image_tag pic.image.url(:medium)), pic

:javascript
  $('.star-rating').raty({
    path: '/public/images/ratyrate',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });

  window.onbeforeunload = clearHeroImage;
  function clearHeroImage() {
    console.log("removing hero Image");

    // check for existence of child image
    //
    var myNode = document.getElementById("heroImage");
    myNode.innerHTML = '';

    return;
  }