config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }

  put "like_user/:id", to: "profiles#upvote", as: :like_user

  resources :pictures do
    member do
      put "like", to: "pictures#upvote"
    end
  end

  # custom routes for users
  get '/users/:id/' => 'users#show', :as => :user
  patch '/users/:id/' => 'users#follow'
  get '/users/' => 'users#index', :as => :all_users

  # custom route for landing page
  get '/home' => 'pictures#landing', :as => :home

  # custom bubble bar search route
  get '/bubbleBar', :to => 'pictures#bubbleBarSearch'

  # root "pictures#landing"
  root "pictures#landing"

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  # make searchable
  #
  searchkick word_start: [:title,:description]

  # exclude rating from searches until I figure out
  # how to avoid the mapper_parsing/number_format_exception
  def search_data
    attributes.except(:rating)
  end

  acts_as_votable

  belongs_to :user


  has_attached_file :originalImage,
    default_url: "/images/:style/missing.png",
    storage: :filesystem,
    path: ":rails_root/clientAssets/:class/:attachment/:id_partition/:style/:filename"
  validates_attachment_content_type :originalImage, content_type: /\Aimage\/.*\z/

  # has_attached_file :image, styles: { medium: "300x300>", small: "150x150>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_attached_file :image,
    styles: { medium: "300x300>", small: "150x150>", thumb: "100x100>" },
    default_url: "/images/:style/missing.png",
    storage: :filesystem,
    path: "/system/:class/:attachment/:id_partition/:style/:filename"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  has_attached_file :publicImage,
    styles: { medium: "300x300>", small: "150x150>", thumb: "100x100>" },
    default_url: "/images/:style/missing.png",
    storage: :filesystem,
    path: "/system/:class/:attachment/:id_partition/:style/:filename"
  validates_attachment_content_type :publicImage, content_type: /\Aimage\/.*\z/



  has_many :keywords

  # additional attr for keywords, which are a separate table
  #
  attr_accessor :keywords

  ####################
  # public methods

  def getImageUrl
    url = self.image.url
  end
  def readImageFile
    img = Magick::Image.read(self.image.path).first
  end

  def getPublicImageUrl
    url = self.publicImage.url
  end
  def getPublicImageFile
    img = Magick::Image.read(self.publicImage.path).first
  end

  def getOriginalImageFile
    img = Magick::Image.read(self.originalImage.path).first
  end

  def watermarkImage(original_file, watermark_file)
    #
    # put code to resize the watermark file to match the original file here
    #
    # make a new watermarked image using the composite method
    img = original_file.composite(watermark_file, Magick::CenterGravity, Magick::SoftLightCompositeOp)
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  include Keywords
  include Watermark

  before_action :find_picture, only: [:show, :edit, :update, :destroy, :upvote]

  respond_to :js, :json, :html

  def autocomplete
    render json: Picture.search(params[:query], autocomplete: true, limit: 10).map(&:title)
    # render json: Picture.search(params[:query], autocomplete: true, limit: 10).map(&:title,&:description)
  end

  def bubbleBarSearch
    redirect_to pictures_path(:srchterm => params[:srchterm])
  end

  def create
    @picture = current_user.pictures.build(picture_params)

    if @picture.save

      # now do keyword creation
      #
      keywords = Keywords.keywordStringToKeywords(picture_params[:keywords])

      msg = ""
      keywords.each do |kw|
        keyword = Keyword.new do |x|
          x.picture_id = @picture.id
          x.word = kw
        end
        if !keyword.save
          msg = "keyword #{kw} add failure. "
        end
      end

      redirect_to @picture, notice: "Successfully Created new Image" + msg
    else
      render "new"
    end
  end

  def destroy
    # first delete all related keywords
    #
    keywords = Keyword.where(:picture_id => @picture.id)
    keywords.each do |kw|
      kw.destroy
    end

    @picture.destroy
    redirect_to root_path
  end

  def edit
    # get and dsiplay any existing keywords
    #
    keywords = Keyword.where(:picture_id => @picture.id)

    @keywordString = Keywords.keywordArrayToKeywordString(keywords)
    # add double quotes to any keywords containing whitespace
    # before concatenating them onto the string
    #
    # keywords.each do |kw|
    #   test = kw.word =~ /\s+/
    #   if test.nil?
    #     @keywordString += " #{kw.word} "
    #   else
    #     @keywordString += " \"#{kw.word}\" "
    #   end
    # end
  end

  def index

    # initialize the pictures array
    #
    @pictures = Picture.first
    if params[:srchterm].present?

      # if the search button was hit, search pictures for the terms
      @pictures = []
      results = Picture.search(params[:srchterm], operator: "or", page: params[:page])
      results.each do |x|
        @pictures << x
      end

      # also search keywords for the search terms
      #
      keywords = Keyword.search(params[:srchterm], operator: "or", page: params[:page])

      # retrieve images based on keywords
      #
      keywords.each do |kw|
        pics = Picture.where(:id => kw.picture_id)
        pics.each do |pic|
          # only add to results if unique
          #
          if !@pictures.include? pic
            @pictures << pic
            # @pictures << Watermark.textmarkImage(pic.image.url)
          end
        end
      end

    else
      @pictures = Picture.all.order("RANDOM()")
      # @pictures = Watermark.watermarkArray Picture.all.order("RANDOM()")
    end

  end

  def landing
    @pictures = Picture.all.order("RANDOM()")
    # @pictures = Watermark.watermarkArray Picture.all.order("RANDOM()")
    if params[:srchterm].present?
      redirect_to pictures_path(params)
    # else
    #   @pictures = Picture.all.order("RANDOM()")
    end

    @artMonth = User.first

    # information for featured artist
    # currently we need a system for designating that artist
    # right now its just the first user
    #
    @artMonthStuff ||= []
    if @artMonth.present?
      fivePix = Picture.where(:user_id => @artMonth.id).limit(5)
      if (fivePix.length > 0)
        @featPix = fivePix[0]
        fivePix.each_with_index do | pix, i |
          if i > 0
            # @artMonthStuff << Watermark.textmarkImage(pix.image.url)
            @artMonthStuff << pix
          end
        end
      end
    end
  end

  def new
    @picture = current_user.pictures.build
    @keywordString = ""
  end

  def show
    @keywords = Keyword.where(:picture_id => @picture.id)
  end

  def update

    if @picture.update(picture_params)

      # get list of possibly changed keywords
      #
      editKeywords = keywordStringToKeywords(picture_params[:keywords])

      # make list of existing keywords
      #
      keywordArray = Keyword.where(:picture_id => @picture.id)
      keywords = keywordStringToKeywords(keywordArrayToKeywordString(keywordArray))

      # compare the two arrays for changes
      #
      deletedKeywords = keywords - editKeywords
      newKeywords = editKeywords - keywords

      # delete any removed keywords
      #
      deletedKeywords.each do |kw|
        toBeDeleted = Keyword.where(:picture_id => @picture.id, :word => kw)
        toBeDeleted.each do |x|
          x.destroy
        end
      end

      # add any new keywords
      #
      msg = ""
      newKeywords.each do |kw|
        keyword = Keyword.new do |x|
          x.picture_id = @picture.id
          x.word = kw
        end
        if !keyword.save
          msg = "keyword #{kw} add failure. "
        end
      end

      redirect_to @picture, notice: "Image was successfully updated " + msg
    else
      render "edit"
    end
  end

  def upvote
    @picture.upvote_by current_user
    redirect_to :back
  end

private
  def picture_params
    params.require(:picture).permit(:title, :description, :image, :keywords)
  end

  def find_picture
    @picture = Picture.find(params[:id])
  end

end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_filter.html.haml
.row
  .col-md-5
    %span5#mediaType
      .row-fluid
        .col-md-2
          %input.filterBar#images{'type' => 'checkbox', 'name'=>'images', 'value'=>'images'}
            %label.filterBar#imagesChk{'for'=>'images'}
        .col-md-2
          %input.filterBar#illustration{'type' => 'checkbox', 'name'=>'illustration', 'value'=>'illustration'}
            %label.filterBar#illustrationChk{'for'=>'illustration'}
        .col-md-2
          %input.filterBar#video{'type' => 'checkbox', 'name'=>'video', 'value'=>'video'}
            %label.filterBar#videoChk{'for'=>'video'}
        .col-md-2
          %input.filterBar#audio{'type' => 'checkbox', 'name'=>'audio', 'value'=>'audio'}
            %label.filterBar#audioChk{'for'=>'audio'}
        .col-md-2
          %input.filterBar#animation{'type' => 'checkbox', 'name'=>'animation', 'value'=>'animation'}
            %label.filterBar#animationChk{'for'=>'animation'}
    .row
      .col-md-3
        %input.filterBar#portrait{'type' => 'checkbox', 'name'=>'portrait', 'value'=>'portrait'}
          %label.filterBar#portraitChk{'for'=>'portrait'}
      .col-md-3
        %input.filterBar#landscape{'type' => 'checkbox', 'name'=>'landscape', 'value'=>'landscape'}
          %label.filterBar#landscapeChk{'for'=>'landscape'}
      .col-md-3
        %input.filterBar#square{'type' => 'checkbox', 'name'=>'square', 'value'=>'square'}
          %label.filterBar#squareChk{'for'=>'square'}
      .col-md-3
        %input.filterBar#panorama{'type' => 'checkbox', 'name'=>'panorama', 'value'=>'panorama'}
          %label.filterBar#panoramaChk{'for'=>'panorama'}
    .row
      .col-md-3
        %input.filterBar#noP{'type' => 'checkbox', 'name'=>'noP', 'value'=>'noP'}
          %label.filterBar#noPChk{'for'=>'noP'}
      .col-md-3
        %input.filterBar#oneP{'type' => 'checkbox', 'name'=>'oneP', 'value'=>'oneP'}
          %label.filterBar#onePChk{'for'=>'oneP'}
      .col-md-3
        %input.filterBar#twoP{'type' => 'checkbox', 'name'=>'twoP', 'value'=>'twoP'}
          %label.filterBar#twoPChk{'for'=>'twoP'}
      .col-md-3
        %input.filterBar#grpP{'type' => 'checkbox', 'name'=>'grpP', 'value'=>'grpP'}
          %label.filterBar#grpPChk{'for'=>'grpP'}
  .col-md-5
    .row
      .col-md-3
        %input.filterBar#man{'type'=>'checkbox', 'name'=>'man', 'value'=>'man'}
          %label.filterBar#manChk{'for'=>'man'}
        %input.filterBar#dog{'type' => 'checkbox', 'name'=>'dog', 'value'=>'dog'}
          %label.filterBar#dogChk{'for'=>'dog'}
        %input.filterBar#free{'type' => 'checkbox', 'name'=>'free', 'value'=>'free'}
          %label.filterBar#freeChk{'for'=>'free'}
      .col-md-3
        %input.filterBar#woman{'type' => 'checkbox', 'name'=>'woman', 'value'=>'woman'}
          %label.filterBar#womanChk{'for'=>'woman'}
        %input.filterBar#cat{'type' => 'checkbox', 'name'=>'cat', 'value'=>'cat'}
          %label.filterBar#catChk{'for'=>'cat'}
        %input.filterBar#dollar{'type' => 'checkbox', 'name'=>'dollar', 'value'=>'dollar'}
          %label.filterBar#dollarChk{'for'=>'dollar'}
      .col-md-3
        %input.filterBar#child{'type' => 'checkbox', 'name'=>'child', 'value'=>'child'}
          %label.filterBar#childChk{'for'=>'child'}
        %input.filterBar#fit{'type' => 'checkbox', 'name'=>'fit', 'value'=>'fit'}
          %label.filterBar#fitChk{'for'=>'fit'}
        %input.filterBar#levIII{'type' => 'checkbox', 'name'=>'levIII', 'value'=>'levIII'}
          %label.filterBar#levIIIChk{'for'=>'levIII'}
      .col-md-3
        %input.filterBar#meals{'type' => 'checkbox', 'name'=>'meals', 'value'=>'meals'}
          %label.filterBar#mealsChk{'for'=>'meals'}
        %input.filterBar#special{'type' => 'checkbox', 'name'=>'special', 'value'=>'special'}
          %label.filterBar#specialChk{'for'=>'special'}
        %input.filterBar#levIV{'type' => 'checkbox', 'name'=>'levIV', 'value'=>'levIV'}
          %label.filterBar#levIVChk{'for'=>'levIV'}
  .col-md-2
    .row
      %input{'type' => 'checkbox', 'name'=>'pallette', 'value'=>'pallette', 'id'=>"palleteChk"}
        %label.filterBar{'for'=>'pallette'}
          Pallette
      .srchColorPicker
        %input{ 'type'=>'text' , :id => 'flat'}
    .row
      %button.btn.btn-primary{ :id => "filterSubmitBtn", :type => "submit"}
        Submit

-#:javascript
-#  $("#flat").spectrum({
-#      flat: true,
-#      showInput: true,
-#      showButtons: false,
-#      containerClassName: 'awesome'
-#  });

-#  $("#flatClearable").spectrum({
-#      flat: true,
-#      showInput: true,
-#      allowEmpty:true,
-#      containerClassName: 'awesome'
-#  });

:javascript
  $(document).ready( function () {
    $("#flat").spectrum({
      containerClassName: 'cPicker',
      showButtons: false,
      flat: true,
      showInput: true,
      appendTo: '.srchColorPicker',
      preferredFormat: "hex3"
    });

    $("#flatClearable").spectrum({
      flat: true,
      showInput: true,
      allowEmpty:true
    });
  });

app/views/pictures/_form.html.haml
= simple_form_for @picture, html: { multipart: true } do |f|
  - if @picture.errors.any?
    #errors
      %h2
      = pluralize(@picture.errors.count, "error")
      prevented this picture from saving
      %ul
        - @picture.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :image, input_html: { class: 'form-control', as: :file }

  .form-group
    = f.input :title, input_html: { class: 'form-control' }

  .form-group
    = f.input :description, input_html: { class: 'form-control' }

  .form-group
    = f.input :keywords, input_html: { class: 'form-control', as: :textarea, :placeholder => @keywordString }

  = f.button :submit, class: "btn btn-primary"

app/views/pictures/edit.html.haml
.col-md-6.col-md-offset-3

  %h1 Edit Picture
  = image_tag @picture.image.url(:medium)

  = render 'form'

  = link_to "Cancel", picture_path

app/views/pictures/index.html.haml
.container.signupTop
  .row.center
    %form.navbar-form{ :role => "search"}
    = form_tag root_path, class: "form-inline", method: :get do
      .input-group.input-group-lg
        - if params[:srchterm].present?
          .input-group-btn
            = link_to "clear", root_path, class: "btn btn-default"
        = text_field_tag :srchterm, params[:srchterm], class: "form-control", id: "srchterm", autocomplete: "on", :placeholder => "Enter Keywords: eg, blue kitten"
        .input-group-btn
          %button.btn.btn-primary{ :type => "submit"}
            %i.glyphicon.glyphicon-search
  .row
    .picGalleryContainer
      .col-md-12
        #picGallery.transitions-enabled.infinite-scroll
          - @pictures.each_with_index do |pic,i|
            = link_to pic do
              .picTile{:id => "picTile_#{i}"}
                = image_tag pic.image.url(:small), :id => "boximg_#{i}"
                :javascript
                  markImg('#{asset_path pic.image.url(:small)}','picTile_#{i}', '#{asset_path "watermark_temp.png"}');
:javascript
  /*  set landingGal's height to be joinUp's height */
  var gallery = document.getElementById('picGallery'),
  resizeFn = function(){
    limitElementHeightToWindow("#picGallery",300);
  };
  addResizeListener(gallery, resizeFn);

app/views/pictures/index2.html.haml
      .input-group.add-on
        %input.form-control#srchterm{ :placeholder => "Enter Keywords: eg, blue kitten", :name => "srchterm", :type => "text" }
        .input-group-btn
          %button.btn.btn-default{ :type => "submit" }
            %i.glyphicon.glyphicon-search



              = link_to (image_tag thing.image.url(:medium)), thing

-#              = link_to (image_tag(thing.image.url(:medium), :size=>"300x300")), thing


.container
  #Images
  .col-md-3
    .categoryColumn
      .page-heading
        Most Viewed Images
      - @pictures.each do |pic|
        .image-frame
          = link_to (image_tag pic.image.url(:medium)), pic

  #Videos
  .col-md-3
    .categoryColumn
      .page-heading
        Most Viewed Videos
      - @pictures.each do |pic|
        .image-frame
          = link_to (image_tag pic.image.url(:medium)), pic

  #Code
  .col-md-3
    .categoryColumn
      .page-heading
        Most Viewed Code
      - @pictures.each do |pic|
        .image-frame
          = link_to (image_tag pic.image.url(:medium)), pic

  #Animation
  .col-md-3
    .categoryColumn
      .page-heading
        Most Viewed Animations
      - @pictures.each do |pic|
        .image-frame
          = link_to (image_tag pic.image.url(:medium)), pic

%form.navbar-form{ :role => "search"}
   .input-group.add-on
      %input.form-control#srch-term{ :placeholder => "Search", :name => "srch-term", :type => "text" }
      .input-group-btn
        button.btn.btn-default{ :type => "submit" }
          %i.glyphicon.glyphicon-search

          =link_to icon("glyphicon-play"), clue_path(@question), {class: "btn btn-lg", :type => "submit"}


  .row
    .col-md-12
      .categoryColumn#landingMosaic
        - @pictures.each do |pic|
          .panel.panel-default
            = link_to (image_tag pic.image.url(:thumb)), pic

app/views/pictures/landing.html.haml
.container
  .row.center.landingPad
    %p.landingTextColor
      What are you looking for?
    %form.navbar-form{ :role => "search", :id => "searchForm"}
      = form_tag root_path, class: "form-inline", method: :get do
        .input-group.input-group-lg
          - if params[:srchterm].present?
            .input-group-btn
              = link_to "clear", root_path, class: "btn btn-default"
          = text_field_tag :srchterm, params[:srchterm], class: "form-control", id: "srchterm", autocomplete: "on", :placeholder => "Enter Keywords: eg, blue kitten"
          .input-group-btn
            %button.btn.btn-primary.btnShadow{ :type => "submit"}
              %i.glyphicon.glyphicon-search
            %button.btn.btn-primary.btnShadow{ :id => "filterBtn" }
              %i.fa.fa-plus{ "aria-hidden" => "true", :id => "filterIcon"}
    .filter
      = render 'filter'
  .row.landingPad
    .col-md-6
      .categoryColumn#landingGal
        #pictures.transitions-enabled
          - @pictures.each_with_index do |pic,i|
            = link_to pic do
              .box{:id => "box_#{i}"}
                = image_tag pic.image.url(:small), :id => "boximg_#{i}"
                :javascript
                  $(document).ready( function () {
                    markImg('#{asset_path pic.image.url(:small)}','box_#{i}','#{asset_path "watermark_temp.png"}');
                  });

    .col-md-6
      .categoryColumn#joinUp
        .landingBlurb
          .lpageHeading
            ARTISTS
          %p.landingTextColor
            Earn what you deserve. Join the world's best marketplace that celebrates artists.
          %br
          - if !user_signed_in?
            %p.landingBtn
              = link_to "Join as Contributor", new_user_registration_path, :id => "landingBtn"
          %br
          .lpageHeading
            CLIENTS
          %p.landingTextColor
            Assets available for every price range. Not the same old pictures and illustrations. See new artists.
          %br
          - if !user_signed_in?
            %p.landingBtn
              = link_to "Join to Download", new_user_registration_path, :id => "landingBtn"
          %br
          %p.landingTextColor
            popEFX is an artist community by artists for artists and clients of every kind. Join today!
          %br
  .bubbleBar
    #bubbles
  - if (@artMonth.present?)
    .row.landingPad
      .container-fluid#featured
        %p.landingTextColor
          Artist of the Month:
          = link_to @artMonth.username, "/users/#{@artMonth.id}", :class => "landingLink"
        - if (@featPix.present?)
          .row
            = link_to @featPix do
              .featuredTile#featuredPrime
                :javascript
                  featureFit("featuredPrime", "#{@featPix.image.url}", 1);
          - if (@artMonthStuff.present?)
            .row
              - @artMonthStuff.each_with_index do |thing, i|
                .col-md-3
                  = link_to thing do
                    .featuredTile{:id => "featTile#{i}"}
                      :javascript
                        featureFit("featTile" + "#{i}", "#{thing.image.url(:medium)}", 4);
          %p.pull-right.landingTextColor
            = link_to "see more", @artMonth, :class => "landingLink"

  .row
    %h1.center.collectionsLink.landingPad
      View Collections
:javascript
  $(document).ready( function () {
    limitHeight("landingGal","joinUp");
    /*  set landingGal's height to be joinUp's height */
    var joinUp = document.getElementById('joinUp'),
    resizeFn = function(){
      limitHeight("landingGal","joinUp");
    };
    addResizeListener(joinUp, resizeFn);
  });

app/views/pictures/new.html.haml
.col-md-6.col-md-offset-3

  %h1 Upload New Image

  = render 'form'

  = link_to "Back", root_path

app/views/pictures/show.html.haml
.row.center
  %form.navbar-form{ :role => "search"}
  = form_tag root_path, class: "form-inline", method: :get do
    .input-group.input-group-lg
      - if params[:srchterm].present?
        .input-group-btn
          = link_to "clear", root_path, class: "btn btn-default"
      = text_field_tag :srchterm, params[:srchterm], class: "form-control", id: "srchterm", autocomplete: "on", :placeholder => "Enter Keywords: eg, blue kitten"
      .input-group-btn
        %button.btn.btn-primary{ :type => "submit"}
          %i.glyphicon.glyphicon-search
.center
  %h2= @picture.title
  .itemFrame#loneImgDiv
    = image_tag @picture.image.url(), :class => "showItem", :style => "display: none"
    %img.showItem#loneImg
      :javascript
        markImg('#{asset_path @picture.image.url()}','loneImg', '#{asset_path "watermark_temp.png"}');

  = link_to like_picture_path(@picture), method: :put, class: "btn btn-default" do
    %span.glyphicon.glyphicon-heart
      =@picture.get_upvotes.size
  %h3
    Description
  %p= @picture.description
  - if @keywords.count > 0
    .center
      %h3
        Keywords:
      %div
        - @keywords.each do |kw|
          .keywrd
            = "#{kw.word}"
    .clearfix
  %h3
    Submitted by
  %p
    = link_to Profile.find_by(user_id: @picture.user.id).brandname, @picture.user
  %hr
  = link_to "Back", root_path
  - if @picture.user == current_user
    = link_to "Edit", edit_picture_path
    = link_to "Delete", picture_path, method: :delete, data: { confirm: "Are you sure?" }
:javascript
  var itemFrame = document.getElementsByClassName('itemFrame')[0];

  var resizeFn = function(){
    $('.showItem').css({
      'max-width': $(window).width() - 100,
      'max-height': $(window).height() - 300
    });
  };
  addResizeListener(itemFrame, resizeFn);