config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }

  put "like_user/:id", to: "profiles#upvote", as: :like_user

  resources :pictures do
    member do
      put "like", to: "pictures#upvote"
    end
  end

  # custom routes for users
  get '/users/:id/' => 'users#show', :as => :user
  patch '/users/:id/' => 'users#follow'
  get '/users/' => 'users#index', :as => :all_users

  # custom route for landing page
  get '/home' => 'pictures#landing', :as => :home

  # custom bubble bar search route
  get '/bubbleBar', :to => 'pictures#bubbleBarSearch'

  # root "pictures#landing"
  root "pictures#landing"

end

app/views/layouts/_footer.html.haml
.container-fluid.navFoot
  .row
    .navbar.navbar-default.navbar-bottom.navFoot
      .container
        .col-md-4
          %ul.nav
            %li= link_to "Contact us", "#"
            %li= link_to "About", "#"
            %li= link_to "FAQ", "#"
        .col-md-4
          %ul.nav
            %li= link_to "Legal Disclaimers", "#"
            %li= link_to "Work for popEFX", "#"
            %li= link_to "Referral Program", "#"
        .col-md-4
          %ul.nav
            %li= render 'layouts/socialMediaBlock'
            - if user_signed_in?
              %li= link_to "Users", user_registration_path(:id => current_user)
              %li= link_to "Edit Profile and Settings", edit_user_registration_path
              %li= link_to "Sign Out", destroy_user_session_path, method: :delete
            - else
              %li= link_to "Log In", new_user_session_path
              %li= link_to "Sign Up", new_user_registration_path
      %p.copyright.pull-right
        © popEFX 2016

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.headgrad{:role =>"navigation"}
  -# Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{:type => "button", "data-target" => "#navbarCollapse", "data-toggle" => "collapse"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar

    = link_to "#{image_tag("popEFX_Logo_Shadow.png", :height => 100)}".html_safe, root_path, :class => "navbar-brand"

  -# Collection of nav links and other content for toggling
  .collapse.navbar-collapse#navbarCollapse
    %ul.nav.navbar-nav.pull-right
      - if user_signed_in?
        %li= link_to "Users", user_registration_path(:id => current_user)
        %li= link_to "Edit Profile and Settings", edit_user_registration_path
        %li= link_to "Upload", new_picture_path
        %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      - else
        %li= link_to "Log In", new_user_session_path
        %li= link_to "Sign Up", new_user_registration_path
    %ul.nav.navbar-nav.navbar-text.pull-right
      %li.tagline
        Don't sell your soul for your art

-#.container
-#  .row.secondaryNav
-#    .center
-#      %ul.nav.navbar-nav
-#        %li= link_to "IMAGES", pictures_path
-#        %li= link_to "ILLUSTRATIONS", "#"
-#        %li= link_to "VIDEO", "#"
-#        %li= link_to "ANIMATION", "#"
-#        %li= link_to "AUDIO", "#"
  -#      %li= link_to "APPS", "#"
  -#      %li= link_to "CODING", "#"

.container
  %ul.catNav
    %li= link_to "IMAGES", pictures_path
    %li= link_to "ILLUSTRATIONS", "#"
    %li= link_to "VIDEO", "#"
    %li= link_to "ANIMATION", "#"
    %li= link_to "AUDIO", "#"
    %li= link_to "FONTS", "#"

app/views/layouts/_header2.html.haml
-#              = link_to (image_tag thing.image.url(:medium)), thing


.container-fluid
  .row-fluid
    .span12
      .span2.linkWidth
        %ul.unstyled
          %li GitHub
          %li= link_to "Contact & support", "#"
          %li= link_to "About Us", "#"
          %li= link_to "FAQ", "#"
      .span2.linkWidth
        %ul.unstyled
          %li Applications
          %li= link_to "Legal Disclaimer", "#"
          %li= link_to "Work for popEFX", "#"
          %li= link_to "Referral Program", "#"
      .span2.linkwidth
        %ul.unstyled
        %li= link_to "Social Media Block", "#"
  %hr
  .row-fluid
    %p.muted.pull-right
      © 2016 popEFX. All rights reserved


%nav.navbar.navbar-default.maintheme-link.headgrad
  .container-fluid
    .navbar-header
      = link_to "#{image_tag("popEFX_logo.png", :height => 100)}".html_safe, root_path, :class => "navbar-brand"
      %p.navbar-text.navbar-right
        Dont sell your soul for your art
  .col
    .navbar.navbar-header
      %ul.nav.navbar-nav
        %li= link_to "IMAGES", new_picture_path
        %li= link_to "ILLUSTRATIONS", "#"
        %li= link_to "VIDEO", "#"
        %li= link_to "ANIMATION", "#"
        %li= link_to "APPS", "#"
        %li= link_to "CODING", "#"



<div class="navbar">
  <div class="navbar-inner">
    <ul class="nav">
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
    </ul>
  </div>
</div>

.navbar
  .navbar-inner
    %ul.nav
      %li= link_to "IMAGES", new_picture_path
      %li= link_to "ILLUSTRATIONS", "#"
      %li= link_to "VIDEO", "#"
      %li= link_to "ANIMATION", "#"
      %li= link_to "APPS", "#"
      %li= link_to "CODING", "#"

app/views/layouts/_socialMediaBlock.html.haml
.footer-social-icons
  %ul.social-icons
    %li= link_to (fa_icon "facebook", :class => "social-icon"), ""
    %li= link_to (fa_icon "twitter", :class => "social-icon"), ""
    %li= link_to (fa_icon "rss", :class => "social-icon"), ""
    %li= link_to (fa_icon "youtube", :class => "social-icon"), ""
    %li= link_to (fa_icon "linkedin", :class => "social-icon"), ""
    %li= link_to (fa_icon "google-plus", :class => "social-icon"), ""

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title PopEFX
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js"
  = javascript_include_tag "http://code.jquery.com/ui/1.10.2/jquery-ui.js"
  = javascript_include_tag "https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"
  = javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.jquery.js"
  %link{:rel => "stylesheet", :href => "http://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"}
  = csrf_meta_tags
%body
  = render 'layouts/header'


  .container.maintheme
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"

    .heroImage#heroImage
    = yield

  = render 'layouts/footer'

app/views/layouts/stub.html.haml
%h1= This is a Stub page